apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache-namespace
spec:
  selector:
    app: apache-label
  ports:
    - protocol: TCP
      port: 80                      #exposed port in cluster
      targetPort: 80                  #container port
